language: node_js

node_js:
 - "node"

before_install:
  - npm i -g codacy-coverage
  - npm i -g codecov

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run test

after_success:
  - codecov
  - cat coverage/lcov.info | codacy-coverage

before_deploy:
  - cd dist

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  skip_cleanup: true
